spring.datasource.url=jdbc:${MYSQL_URL}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10